<?php
/**
 * Dc_Translator
 * 
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Dc
 * @package    Dc_Translator
 * @copyright  Copyright (c) 2012-2015 Damián Culotta. (http://www.damianculotta.com.ar/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (Mage::getStoreConfig('translator/bing/enabled')): ?>
<script type="text/javascript">
//<![CDATA[
DcTranslate = new DcTranslator('<?php echo $this->getAjaxUrl(); ?>', 'en', '<?php echo $this->getLocale(); ?>');
//]]>
</script>
<?php endif; ?>