<?php
/**
 * Dc_Translator
 * 
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Dc
 * @package    Dc_Translator
 * @copyright  Copyright (c) 2014 Damián Culotta. (http://www.damianculotta.com.ar/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-customer-view"><?php echo Mage::helper('translator')->__('Package Information') ?></h4>
    </div>
    <fieldset>
        <table class="box-wide">
            <tr>
                <td><strong><?php echo $this->__('Package:') ?></strong></td>
                <td><?php echo $this->getPackageName(); ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Locale Code:') ?></strong></td>
                <td><?php echo $this->getPackage()->getLocale(); ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Created At:') ?></strong></td>
                <td><?php echo $this->formatDate($this->getPackage()->getCreatedAt(), 'short', true); ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Last Update:') ?></strong></td>
                <td><?php echo $this->formatDate($this->getPackage()->getUpdatedAt(), 'short', true); ?></td>
            </tr>
        </table>
    </fieldset>
</div>